services:
  - type: worker
    name: referral-bot
    env: python
    buildCommand: "pip install -r requirements.txt"
    startCommand: "python main.py"
    envVars:
      - key: BOT_TOKEN
        value: "8298808592:AAGAARB2_bWJoqYPJB4uzF0lkImt3-HtKVw"
      - key: ADMIN_ID
        value: "6643046428"
